[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"

solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

bytecode_hash = "none"
cbor_metadata = false

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

fs_permissions = [{ access = "read", path = "./" }]

[fuzz]
runs = 10000
max_test_rejects = 65536

[invariant]
runs = 256
depth = 64
fail_on_revert = false
call_override = false

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"

[rpc_endpoints]
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"

[etherscan]
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
